### ISSUE TITLE
not working with NUXT

### ISSUE THREAD

**Issue by heshamelmasry77** [hjl19911127/vue-drawer-layout#13]
{ TypeError: Cannot read property 'middleware' of undefined
    at module.exports.__webpack_exports__.default (.nuxt/server.js:115:0)
    at process._tickCallback (internal/process/next_tick.js:68:7) statusCode: 500, name: 'TypeError' }

**Comment by hjl19911127** [comment]
Thanks for your feedback.I'm trying to confirm this problem.

**Comment by hjl19911127** [comment]
Would you mind offering me more information about this problem ?Looks like your problem is about a variable named 'middleware' .Could you show me some source code around this problem?

**Comment by sbefort** [comment]
It does not work with Nuxt because Nuxt is for both server-side and client-side rendering.  The component references the `window` object, which is not available on the server.  We can fix this by adding conditions to check whether or not the component has been loaded on the server or client.

What is the purpose of this code?

`window.addEventListener("test", null, opts);`

It's on line 23 of DrawerLayout.vue.

**Comment by hjl19911127** [comment]
It a detection of passive event.

**Comment by hjl19911127** [comment]
I found that it is wrapped in `try..catch` block. Will it still be wrong? So do you got any suggestion about the question?

**Comment by sbefort** [comment]
I don't think your code should reference the `window` object until the `mounted` life cycle hook is called.  That will guarantee that the component has been loaded in the browser rather than the server.  If you can do that, your component will work with server-side rendering frameworks like Nuxt.

`mounted()` is only executed on the client side.

**Comment by hjl19911127** [comment]
I publish v0.3.5 that put it in mounted hook.Hope you try it.:)
